gruppo: prodotto
foto:
  - immagine: /images/portfolio/prodotto/Bocelli1831-2024Bottles-Blackbackground1.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Bocelli1831-2024Bottles-Blackbackground2.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Bocelli1831-2024Bottles-Blackbackground3.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Bocelli1831-2024Bottles-Blackbackground4.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Bocelli1831-2024Bottles-Blackbackground5.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Bocelli1831-2024Bottles-Blackbackground7.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Bocelli1831-2024Bottles-Blackbackground8.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Bocelli1831-2024Bottles-Blackbackground9.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/DSC6555.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/DSC6928.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/DSC7600.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/DSC7601-copia.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/DSC7610-copia.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/DSC7618-copia.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/DSC8032-copia.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Light-painting00001.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Light-painting00002.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Light-painting00003.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/Light-painting00007.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/accessori-geppetto-foto00001.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/accessori-geppetto-foto00003.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/accessori-geppetto-foto00004.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/accessori-geppetto-foto00005.jpg
    titolo: ""
  - immagine: /images/portfolio/prodotto/accessori-geppetto00013.jpg
    titolo: ""
